src/main/java/com/pb/creditbh/model/entity/Client.java
package com.pb.creditbh.model.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Entity Client
 *
 * @author Dmitriy Slobodenyuk
 */
@XmlRootElement()
public class Client implements Serializable {

    private long idClient;
    private String inn;
    private String firstName;
    private String secondName;
    private String lastName;
    private long dateBorn;
    private String serialPassport;
    private String numberPassport;
    private String image = "/resources/image/ava_def.png";
    private List<Credit> listCredits;
    private String dateFormat = "yyyy-dd-MM";

    public Client() {
    }

    public Client(int idClient, String inn, String firstName, String secondName,
            String lastName, long dateBorn, String serialPassport, String numberPassport) {
        this.idClient = idClient;
        this.inn = inn;
        this.firstName = firstName;
        this.secondName = secondName;
        this.lastName = lastName;
        this.dateBorn = dateBorn;
        this.serialPassport = serialPassport;
        this.numberPassport = numberPassport;
    }

    public long getIdClient() {
        return idClient;
    }

    public void setIdClient(long idClient) {
        this.idClient = idClient;
    }

    public String getInn() {
        return inn;
    }

    public void setInn(String inn) {
        this.inn = inn;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getSecondName() {
        return secondName;
    }

    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {

        this.lastName = lastName;
    }
    public String getDateBornToString() {
        String date = "";
        Date d = new Date(dateBorn);
        SimpleDateFormat formatter = new SimpleDateFormat(dateFormat);
        date = formatter.format(d);
        return date;
    }

    public long getDateBorn() {
        return dateBorn;
    }

    public void setDateBorn(long dateBorn) {
        this.dateBorn = dateBorn;
    }

    public String getSerialPassport() {
        return serialPassport;
    }

    public void setSerialPassport(String serialPassport) {
        this.serialPassport = serialPassport;
    }

    public String getNumberPassport() {
        return numberPassport;
    }

    public void setNumberPassport(String numberPassport) {
        this.numberPassport = numberPassport;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        if (image != null) {
            this.image = image;
        }
    }

    @XmlElement(name = "credit")
    public List<Credit> getListCredits() {
        return listCredits;
    }

    public void setListCredits(List<Credit> listCredits) {
        this.listCredits = listCredits;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + (this.inn != null ? this.inn.hashCode() : 0);
        hash = 29 * hash + (this.serialPassport != null ? this.serialPassport.hashCode() : 0);
        hash = 29 * hash + (this.numberPassport != null ? this.numberPassport.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Client other = (Client) obj;
        if ((this.inn == null) ? (other.inn != null) : !this.inn.equals(other.inn)) {
            return false;
        }
        if ((this.serialPassport == null) ? (other.serialPassport != null) : !this.serialPassport.equals(other.serialPassport)) {
            return false;
        }
        if ((this.numberPassport == null) ? (other.numberPassport != null) : !this.numberPassport.equals(other.numberPassport)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Client{"
                + "inn=" + inn
                + ", firstName=" + firstName
                + ", secondName=" + secondName
                + ", lastName=" + lastName
                + ", dateBorn=" + dateBorn
                + ", serialPassport=" + serialPassport
                + ", numberPassport=" + numberPassport + '}';
    }
}

src/main/java/com/pb/creditbh/model/entity/Credit.java
package com.pb.creditbh.model.entity;

import com.pb.creditbh.model.entity.catalog.Bank;
import com.pb.creditbh.model.entity.catalog.Currency;
import java.io.Serializable;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Entity Credit
 *
 * @author Dmitriy Slobodenyuk
 */
@XmlRootElement()
public class Credit implements Serializable {

    private long idCredit;
    private Currency currency;
    private Bank bank;
    private long client;
    private BigDecimal baseAmount;
    private long creditDateIssue;
    private BigDecimal creditCurrBody;
    private long creditEnd;
    private String outDelay;
    private String dateFormat = "yyyy-dd-MM";

    public Credit() {

    }

    public Credit(int idCredit, Currency idCurrency, Bank idBank, long idClient,
            BigDecimal baseAmount, long creditDateIssue, BigDecimal creditCurrBody, long creditEnd, String outDelay) {
        this.idCredit = idCredit;
        this.currency = idCurrency;
        this.bank = idBank;
        this.client = idClient;
        this.baseAmount = baseAmount;
        this.creditDateIssue = creditDateIssue;
        this.creditCurrBody = creditCurrBody;
        this.creditEnd = creditEnd;
        this.outDelay = outDelay;
    }

    public long getIdCredit() {
        return idCredit;
    }

    public void setIdCredit(long idCredit) {
        this.idCredit = idCredit;
    }

    @XmlElement(name = "currency")
    public Currency getCurrency() {
        return currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    @XmlElement(name = "bank")
    public Bank getBank() {
        return bank;
    }

    public void setBank(Bank bank) {
        this.bank = bank;
    }

    public long getClient() {
        return client;
    }

    public void setClient(long client) {
        this.client = client;
    }

    public BigDecimal getBaseAmount() {
        return baseAmount;
    }

    public void setBaseAmount(BigDecimal baseAmount) {
        this.baseAmount = baseAmount;
    }

    public long getCreditDateIssue() {
        return creditDateIssue;
    }

    public void setCreditDateIssue(long creditDateIssue) {
        this.creditDateIssue = creditDateIssue;
    }

    public BigDecimal getCreditCurrBody() {
        return creditCurrBody;
    }

    public void setCreditCurrBody(BigDecimal creditCurrBody) {
        this.creditCurrBody = creditCurrBody;
    }

    public long getCreditEnd() {
        return creditEnd;
    }

    public void setCreditEnd(long creditEnd) {
        this.creditEnd = creditEnd;
    }

    public String getOutDelay() {
        return outDelay;
    }

    public void setOutDelay(String outDelay) {
        this.outDelay = outDelay;
    }

    public String getDateIssueToString() {
        String date = "";
        Date d = new Date(creditDateIssue);
        SimpleDateFormat formatter = new SimpleDateFormat(dateFormat);
        date = formatter.format(d);
        return date;
    }

    public String getDateEndToString() {
        String date = "";
        Date d = new Date(creditEnd);
        SimpleDateFormat formatter = new SimpleDateFormat(dateFormat);
        date = formatter.format(d);
        return date;
    }

    @Override
    public String toString() {
        return "Банк = " + bank.getBankName() + ", оформлен = " + creditDateIssue;
    }

}

src/main/webapp/WEB-INF/jsp/include/add_bank_form.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<form id="form_add_bank" method="post" class="form-inline">
    <input class="input-large" type="text" name="bank_name" placeholder="Название банка"><br>
    <input class="input-large" type="text" name="bank_code" placeholder="Код банка (6 лат. символов)"><br>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
<span id="status_bank"></span>

src/main/webapp/WEB-INF/jsp/include/add_currency_form.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<form id="form_add_curr" method="post" class="form-inline">
    <input class="input-large" type="text" name="curr_name" placeholder="Название валюты"><br>
    <input class="input-large" type="text" name="curr_code" placeholder="Код валюты (3 лат. символа)"><br>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
<span id="status_curr"></span>

src/main/webapp/WEB-INF/jsp/include/cap_site.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="UTF-8" %>
<div id="head" class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="span2"></div>
                    <div id="head_maket" class="span8">
                        <img class="img_maket">
                        <h1>Бюро Кредитных Историй</h1>
                    </div>
                    <div class="span2"></div>
                </div>
            </div>
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/include/credit_dialog.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<div class="container-fluid">

    <div class="row-fluid">
        <!--   Block adding and editing credits -->
        <div id='form_credit' class="span5">
            <div class="tabbable" style="margin: 5px;"> 
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab3" data-toggle="tab">Редактировать</a></li>
                    <li><a href="#tab4" data-toggle="tab">Добавить</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab3">
                        <input class="span6" type="text" name="ed_body" placeholder="Тело кредита"><span id="id_sp" style="visibility: hidden"></span><br>
                        <label class="lb">Дата погашения :</label>
                        <input id="input_date" class="span6" type="text" name="ed_date_end" placeholder="ГГГГ-ДД-ММ"><span id="date_credit_edit" class="message"></span><br>
                        <label class="lb">Просрочки :</label>
                        <select class="span6" name="ed_delay">
                            <option>Да</option>
                            <option>Нет</option>
                        </select><br>

                        <button type="submit" class="btn btn-primary" onclick="saveModifiedCredit()">
                            Сохранить</button>
                    </div>  

                    <div class="tab-pane" id="tab4">
                        <label class="lb">Банк :<span id="id_cl" style="visibility: hidden">${client.idClient}</span></label>
                        <select class="span6" name="add_bank">
                            <c:forEach items="${listBanks}" var="bank">
                                <option>${bank.bankName}</option>
                            </c:forEach>

                        </select><br>
                        <label class="lb">Валюта :</label>
                        <select class="span6" name="add_curr"> 
                            <c:forEach items="${listCurrency}" var="currency">
                                <option>${currency.currName}</option>
                            </c:forEach>

                        </select><br>
                        <input class="span6" type="text" name="add_bsumm" placeholder="Взнос"><br>
                        <label class="lb">Дата оформления :</label>
                        <input class="span6" type="text" name="add_begin_date" placeholder="ГГГГ-ДД-ММ"><span id="start_date_edit" class="message"></span><br>
                        <label class="lb">Дата погашения :</label>
                        <input class="span6" type="text" name="add_end_date" placeholder="ГГГГ-ДД-ММ"><span id="end_date_edit" class="message"></span><br>
                        
                        <button type="submit" class="btn btn-primary" onclick="saveNewCredit()">Добавить</button>

                    </div>
                </div>
            </div>
        </div>
        <!--  end of block-->

        <!--  beginning of the block list the loans-->
        <div id="list_credit" class="span7">

            <div class="tabbable" style="margin: 5px"> 
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#tab5" data-toggle="tab">Активные кредиты</a>
                    </li>
                    <li>
                        <a href="#tab6" data-toggle="tab">Все кредиты</a>
                    </li>
                </ul>
                <div id ="lst_credit" class="tab-content">
                    <div class="tab-pane active" id="tab5">
                        <div id="list_credit_div">
                            <%@ include file="listCredits.jsp" %>
                        </div>
                    </div>
                    <div class="tab-pane" id="tab6">
                        <div id="credit_all">
                            <%@ include file="listAllCredits.jsp" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

src/main/webapp/WEB-INF/jsp/include/footer.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="UTF-8" %>
<div id="footer">
    <div id="do_footer" class="container-fluid">
        <h1>About</h1>
        <div class="row-fluid">
            <div class="span3"></div>
            <div class="span6">
                <p>© 2015 Privat Bank Software, Inc. All Rights Reserved. Terms of Use and Privacy
                </p>                    
            </div>
            <div class="span3">
            </div>
        </div>
    </div>   
</div>

src/main/webapp/WEB-INF/jsp/include/listAllCredits.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<c:forEach items="${client.listCredits}" var="credit">

    <div id="credit_item" class="row">
        <div class="span6">
            <span>Банк : ${credit.bank.bankName}</span><br>
            <span>Дата выдачи: ${credit.dateIssueToString}</span><br>
            <span>Дата погашения: ${credit.dateEndToString}</span><br>
            <span>Валюта : ${credit.currency.currName}</span><br>
            <span>Тело кредита = ${credit.creditCurrBody}</span><br>
            <span>Просрочки : ${credit.outDelay}</span>
        </div>
        <div class="span6">
            <div class="crd_img"> 
            </div>
        </div>
    </div>
</c:forEach>

src/main/webapp/WEB-INF/jsp/include/listCredits.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<c:forEach items="${listActiveCredits}" var="credit">

    <div id="credit_item" class="row">
        <div class="span6">
            <span id="bnk">Банк : ${credit.bank.bankName}</span><br>
            <span>Дата выдачи: ${credit.dateIssueToString}</span><br>
            <span>Дата погашения: ${credit.dateEndToString}</span><br>
            <span>Валюта : ${credit.currency.currName}</span><br>
            <span>Тело кредита = ${credit.creditCurrBody}</span><br>
            <span>Просрочки : ${credit.outDelay}</span>
        </div>
        <div class="span6">
            <div class="crd_img"> 
            </div>
            <button id="btn_credit_edit" class="btn btn-primary" onclick="editCredit('${credit.idCredit}',
                            '${credit.creditCurrBody}', '${credit.creditEnd}', '${credit.outDelay}'
                            )">Редактировать</button>
        </div>
    </div>
</c:forEach>

src/main/webapp/WEB-INF/jsp/include/navbar.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="UTF-8" %>
<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            <a id="nvb_main" class="blog-nav-item active" href="#">Главная</a>
            <a id="nvb_in" class="blog-nav-item" href="#">Поиск клиентов</a>
            <a id="nvb_admin" class="blog-nav-item" href="#">Панель администратора</a>
            <a class="blog-nav-item" href="#">Контакты</a>
        </nav>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/include/outClient.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<c:forEach items="${listClient}" var="client">

    <div class="container-fluid">
        <div class="row-fluid">
            <div id="itm" class="span12">
                <div class="container-fluid">
                    <div class="row-fluid">
                        <div id="item_photo" class="span6" >                                                        
                        </div>
                        <div class="span6">
                            <label class="lbl_item">ФИО : ${client.firstName} ${client.secondName} ${client.lastName}</label>
                            <label class="lbl_item">Дата рождения : ${client.dateBornToString}</label>
                            <label class="lbl_item">ИНН : ${client.inn}</label>
                            <label class="lbl_item">Паспорт : ${client.serialPassport} ${client.numberPassport}</label>

                            <button id="btn_all" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#allModal">Все Кредиты</button>

                            <div id="allModal" class="" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content" style="background-color: #f2f2f2">
                                        <div class="modal-header " style="background-color: #0480be">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title" id="myModalLabel" style="color: white">Кредиты клиента</h4>
                                        </div>
                                        <div class="modal-body">
                                            <%@ include file="credit_dialog.jsp" %> 
                                            <div id="oper"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</c:forEach>

src/main/webapp/WEB-INF/jsp/include/outError.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div class="container-fluid">
    <div class="row-fluid">
        <div id="item_error" class="span12"> 
            <div class="container-fluid">
                <div class="row-fluid">
                    <div id="message_error" class="span3"></div>
                    <div class="span8" style="margin-top: 15px">
                        <ul style="list-style: none">
                            <li>
                                <i>${message1}</i>
                            </li>
                            <li>
                                <i>${message2}</i>
                            </li>
                        </ul>
                    </div>
                    <div class="span1"></div>
                </div>
            </div>
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/include/status_operation.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<span class="status">Статус :${message}</span>

src/main/webapp/WEB-INF/jsp/include/styles.jsp
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/resources/css/style.css"/>
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/resources/css/bootstrap.css"/>
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/resources/css/bootstrap.css.map"/>
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/resources/css/bootstrap-theme.css"/>
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/resources/css/bootstrap-theme.css.map"/>

<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/jquery.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/bootstrap.js"></script>

<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/find_client.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/navbar.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/foradmin.js"></script>

<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/modal.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/popover.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/transition.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/tooltip.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/ie10-viewport-bug-workaround.js"></script>

src/main/webapp/WEB-INF/jsp/include/success.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!--output message-->
<div class="container-fluid">
    <div class="row-fluid">
        <div id="item_error" class="span12"> 
            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="span3" style="margin-top: 15px;height: 100px;background:  url('${pageContext.request.contextPath}/resources/image/success_icon.png') no-repeat;"></div>
                    <div class="span8" style="margin-top: 15px">
                        <ul style="list-style: none">
                            <li>
                                <i>${message1}</i>
                            </li>
                            <li>
                                <i>${message2}</i>
                            </li>
                        </ul>
                    </div>
                    <div class="span1"></div>
                </div>
            </div>
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/include/text-index.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<p>Бюро кредитных историй» зарегистрировано в 29.07.2014 г. и действует на основе Закона Украины № 2704-IV от 23.06.2005 г. «Об организации формирования и обращения кредитных историй».</p> 

<p>БКИ среди бюро кредитных историй Украины получило лицензию Министерства юстиции Украины от 26.01.2007 г. № 307652 на осуществление деятельности связанной с сбором, обработкой, хранением, защитой, использованием информации, которая составляет кредитную историю.</p>  

<p>Бюро создано в форме общества с ограниченной ответственностью при участии Ассоциации украинских банков, 33 банков, 2 страховых и лизинговой компании и исландской компании Кредитинфо Групп.</p> 

<p>БЮРО ведет кредитные истории юридических и физических лиц и предоставляет банкам и небанковским финансово-кредитным учреждениям большой спектр специализированных систем поддержки принятия решений и управления рисками.</p> 

<p>Потребителями услуг БКИ выступают банки, страховые и лизинговые компании, кредитные союзы, компании, которые предоставляют услуги связи и тому подобное.</p>